### ISSUE TITLE
Doesnt magnet items that are below

### ISSUE THREAD

**Issue by SpeTheof** [MichaelHillcox/Just-a-Magnet-Mod#2]
if the item is 1 block below the one im standing it doesn't climb up sometimes

**Comment by MichaelHillcox** [comment]
It's an issue with the way I am moving the objects. I'm looking to make the mod more intelligent about how it moves items towards you. I'm going to try and make it a lot more like botania's one.

**Comment by SpeTheof** [comment]
I see, it's very useful when farming near water though, they never drop, lava too

**Comment by MichaelHillcox** [comment]
Fixed as of f9239fd
