### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by jprocket45** [MichaelHillcox/Just-a-Magnet-Mod#3]
server crash happening unless im wrong i would assume this needed to be server side and just not client side to use sorry if this is the wrong idea lol   https://pastebin.com/m7GKugBV

**Comment by MichaelHillcox** [comment]
I'll have a look at that. Thanks 👍

**Comment by jprocket45** [comment]
cool thanks hopefully its fixed soon!!!

**Comment by jprocket45** [comment]
just to let you know from others I have spoken with its just updating to the recommended version of forge 99% of people have fixed there mod this way. forge 2555  not sure if this is the case for this but just a little info :)

**Comment by MichaelHillcox** [comment]
What game version is this for @jprocket45 if it's 1.7.10 I've been made aware of it on my other mosts and I'll be updating them all soon

**Comment by jprocket45** [comment]
this is for 1.12.2 @MichaelHillcox

**Comment by MichaelHillcox** [comment]
Ah, Okay then :D

**Comment by MichaelHillcox** [comment]
I've bumped the version and it'll be on curse with in the next 10 minutes
