### ISSUE TITLE
still crashing with update :(

### ISSUE THREAD

**Issue by jprocket45** [MichaelHillcox/Just-a-Magnet-Mod#4]
just wanted to let ya know the fix did not work still crashing 1.12.2 server,thanks for all the hard work!

https://pastebin.com/Vhkz2iFY

**Comment by MichaelHillcox** [comment]
Sorry about that, I've figured it out. Turns out I was being stupid, who would have guessed. I've found and identified the cause of the issue so I'll get working on fixing it :D

**Comment by jprocket45** [comment]
cool hope to see an update soon! ill check it out on the server once its update! :)

**Comment by jprocket45** [comment]
not trying to bug you honestly lol any new info on a release with a fix server side? I tend to keep on mod authors butts when there is a issue sorry lol

**Comment by jprocket45** [comment]
any update on this? im sadly thinking about removing this next update I submit I really like the mod you did a great job with it I will leave it be at this.

**Comment by MichaelHillcox** [comment]
Hi, Sorry about this, I've been ill for the past few days. I'll be booting up all my mods and fixing any issues today or tomorrow.

**Comment by jprocket45** [comment]
ok sounds good ill wait then honestly not trying to be pushy just last mod needed fixed to make my pack stable enough on a server :)  I think since your last update there was a stable version released with forge 2611 dunno if that will help or you want to up the forge version anyways thanks again!

**Comment by MichaelHillcox** [comment]
@jprocket45 Well that was all very silly. I totally forgot to support MP. Thats all sorted now! You can grab the latest file here https://github.com/MichaelHillcox/Just-a-Magnet-Mod/releases/tag/1.12.2-v1.1.1 It'll be on Curse within the hour
