### ISSUE TITLE
No recipe in JEI

### ISSUE THREAD

**Issue by Ravalli03** [MichaelHillcox/Just-a-Magnet-Mod#5]
MC Ver. 1.12.2

Mod Ver. 1.0.1

Doesn't show any recipes in JEI

**Comment by MichaelHillcox** [comment]
Hi, It's not a made item that you have to carry arround. Simply change the settings to the button you'd like and turn it on :D As a quick warning, this does not work on MP servers yet. There should be a patch in the next few days for that.
